mainprefix: "-"
defaultjoinmessage: "**{user} Joined Invited By {Inviter} (Invites: {inv})**"
defaultleavemessage: "**{user} Left, Invited by {inviter}**"
token: "NzYxMTEyMDU5MjgyNDU2NjA2.X3V21w.Oz4PZIESHZQNFSpVdum-7reZAV4"
color: "BLUE"
